#  NumPy Classroom Exercise 

 
**Rules:** Use only **NumPy** (`import numpy as np`). Avoid Python loops unless asked.


In [1]:
# Setup
import numpy as np


**Task 1.1** Create:
- `A` with shape `(3, 4)` of type `float64` containing values `0..11`.
- `B` as a `(4, 1)` column vector of type `int32` containing values `1..4`.
- Without copying, create `A_view` selecting the **last two columns** of `A`. Prove modifying `A_view` also changes `A`.

**Task 1.2** Convert `B` to `float64` **without** changing `B` in place, and explain why `A @ B` fails or succeeds.

In [24]:
# === Your work: 1.1 & 1.2 ===
# Create A, B, A_view as described; then demonstrate the view behavior and try A @ B.
A = np.arange(12, dtype=np.float64).reshape(3, 4)
print("A:\n", A)
B = np.arange(1,5, dtype=np.int32).reshape(4, 1)
print("\nB:\n", B)

A_view = A[:, 2:]
print("\nA_view:\n", A_view)
A_view[1,1] = 26
print("\nChanged A:\n", A)


#task 2
B2 = B.astype(np.float64)
print("\nB float:\n", B2)

try:
    print("\nA @ B:\n", A @ B)
except Exception as e:
    print("Error: ", e)

#When we modified A-view, A also changed because A_view is not a copy, so changing it also changes A because it refers to the same data in memory.
#For b float, we used b2 as another variable to store the float version of b, so it is basically a new array in memory. And this is why b is unchanged.
#I am not sure what you mean by if A @ B works. They do work mathematically, because the matrix multiplication rule is true here
#Since it is (3,4) X (4,1), it would ideally result in a (3,1) matrix and we did that get.
#If it has to do something about the type? Then both float64 and int32 are numeric types, so Numppy handles them correctly?


A:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

B:
 [[1]
 [2]
 [3]
 [4]]

A_view:
 [[ 2.  3.]
 [ 6.  7.]
 [10. 11.]]

Changed A:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6. 26.]
 [ 8.  9. 10. 11.]]

B float:
 [[1.]
 [2.]
 [3.]
 [4.]]

A @ B:
 [[ 20.]
 [136.]
 [100.]]


`X = np.arange(1, 13).reshape(3, 4)`, `w = np.array([1, -1, 1, -1])`

**Task 2.1** Multiply each column of X by the matching weight in w and then add across the row.
The result should be a 1-D array with 3 values (one for each row).
Do this without using any loops.

**Task 2.2** Standardize `X` **column‑wise** to zero mean/unit var using broadcasting. Verify means/stds.
"Standardize” means:

Subtract the mean of each column,

Then divide by that column’s standard deviation.

This makes each column have mean ≈ 0 and standard deviation ≈ 1.

**Task 2.3** Explain why `X + np.array([1, 2])` errors, but `X + np.array([[1],[2],[3]])` works.

In [23]:
# === Your work: 2.1–2.3 ===
X = np.arange(1, 13).reshape(3, 4)
w = np.array([1, -1, 1, -1])
print(X)
print("\n",w)


# 2.1
data = (X * w).sum(axis=1)
print("\ndata:\n", data)

# 2.2
mean = X.mean(axis=0)
std = X.std(axis=0)
X2 = (X - mean)/std
#nomral
print("\nNormal:")
print(mean)
print(std)

#standardized
print("\nStandardized:")
print(X2.mean(axis=0))
print( X2.std(axis=0))

# 2.3 (brief note in a string variable)
reasoning_23 = """
I did forget a bit about broadcasting, but when I reviewed it a bit, the main reason that np.array([1,2]) does not work is because
the last dimensions must match or one of them must be 1. But here the shape of X is (3,4) and the np array is (2,0). This is why it didnt work
On the other hand, np.array([[1],[2],[3]]) has a shape of (3,1), and since the last dimension is 1, it works
"""


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [ 1 -1  1 -1]

data:
 [-2 -2 -2]

Normal:
[5. 6. 7. 8.]
[3.26598632 3.26598632 3.26598632 3.26598632]

Standardized:
[0. 0. 0. 0.]
[1. 1. 1. 1.]



Let `rng = np.random.default_rng(0)` and `Z = rng.normal(0, 1, (5, 6))`.

`Z` becomes a **5×6 matrix** filled with random numbers drawn from the standard normal distribution (mean 0, std 1).  


**Task 3.1** Count how many rows have **≥ 3** strictly positive entries (no loops).

**Task 3.2** Replace negatives with their squares; keep non‑negatives unchanged (vectorized).

In [ ]:
# === Your work: 3.1–3.3 ===
rng = np.random.default_rng(0)
Z = rng.normal(loc=0, scale=1, size=(5, 6))
print(Z)

# 3.1
positiverow = (Z > 0).sum(axis=1)
print(positiverow)

finalrows = (positiverow >= 3).sum()
print(finalrows)

# 3.2
#where function
positiveZ = np.where(Z < 0, Z*Z, Z)
print(positiveZ)



[[ 0.12573022 -0.13210486  0.64042265  0.10490012 -0.53566937  0.36159505]
 [ 1.30400005  0.94708096 -0.70373524 -1.26542147 -0.62327446  0.04132598]
 [-2.32503077 -0.21879166 -1.24591095 -0.73226735 -0.54425898 -0.31630016]
 [ 0.41163054  1.04251337 -0.12853466  1.36646347 -0.66519467  0.35151007]
 [ 0.90347018  0.0940123  -0.74349925 -0.92172538 -0.45772583  0.22019512]]
[4 3 0 4 3]
4
[[0.12573022 0.01745169 0.64042265 0.10490012 0.28694168 0.36159505]
 [1.30400005 0.94708096 0.49524328 1.6012915  0.38847106 0.04132598]
 [5.4057681  0.04786979 1.55229409 0.53621548 0.29621784 0.10004579]
 [0.41163054 1.04251337 0.01652116 1.36646347 0.44248395 0.35151007]
 [0.90347018 0.0940123  0.55279113 0.84957767 0.20951293 0.22019512]]


Create `Y = np.arange(1, 13).reshape(3, 4)`.

**Task 4.1** Use **basic slicing** to extract columns 1..2 and set them to `-99`. Show `Y` changed.


In [ ]:
# === Your work: 4.1–4.2 ===
Y = np.arange(1, 13).reshape(3, 4)
print(Y)

# 4.1
Y[:, 1:3] = -99
print("\n", Y)

#I am not sure what you mean by the columns '1..2'. Do you mean the first and second columns (0-indexed) or the second and third columns?
#I assumed you meant the second and third columns so I used 1:3.




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [[  1 -99 -99   4]
 [  5 -99 -99   8]
 [  9 -99 -99  12]]


Define `a=b=(2,000,000)` random normals.

**Task 5.1** Compute cosine similarity once using **pure Python loops** and once using **NumPy**; time both (use `%timeit`/`%%timeit` in Jupyter).

In [51]:
# === Your work: 7.1 ===
rng = np.random.default_rng(0)
a = rng.normal(size=2_000_000)
b = rng.normal(size=2_000_000)

# Pure Python loops (sketch; be careful—this will be slow)
dot = 0.0
for i in range(len(a)):
    dot += float(a[i]) * float(b[i])
cos_loop = dot / (np.sqrt((a*a).sum()) * np.sqrt((b*b).sum()))
print(cos_loop)


# NumPy vectorized
cos_numpy = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
%timeit a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b))
print(cos_numpy)



-0.00045202468071826125
1.72 ms ± 215 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
-0.0004520246807183116
