In [2]:
import numpy as np

*Question 1*

Create an array x= [1.2.3.4.5].

Compute y = 2x^2 + 3x+ 1 wihtout using any loops

Question. What is the shape of y

In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = 2*x**2 + 3*x + 1           
print(y)
print(y.shape)

#The shape of y is (5) which means it is a one dimensional array with 5 elements.


[ 6 15 28 45 66]
(5,)


*Question 2*

Let
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

b = np.array([10, 20, 30])

Use broadcasting to add b to each row of A. 

Question: What is the resulting array.

In [4]:
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

b = np.array([10, 20, 30])

result = A + b
print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]


*Question 3*

Create a matrix 

A = np.array([[1, 2, 3],
              [4, 5, 6]])

a. Find A.T
b. What are the shapes of A and A.T
c. Verify that (A.T).T == A.

In [9]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.T)

print(A.shape)
print(A.T.shape)

print((A.T).T)

print(np.array_equal((A.T).T, A))

#b) The shaped of A is 2 rows and 3 columnns. The shape of A.T is 3 rows and 2 columbs
#c) Yes, they both are equal and it does make sense because you are basically transposing twice which will give you the original matrix.



[[1 4]
 [2 5]
 [3 6]]
(2, 3)
(3, 2)
[[1 2 3]
 [4 5 6]]
True


*Question 4*

Create 
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[ 7,  8,  9],
              [10, 11, 12]])

a. Compute C @ D
b. What is the shape of this result 


In [12]:
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

D = np.array([[ 7,  8,  9],
              [10, 11, 12]])

result = np.dot(C, D)
print(result)

print(result.shape)

#The shape of the result is a 3x3 matrix. I am not sure if this is correct because I forgot some linear algebra rules, but I would assume they are right.

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]
(3, 3)
